### ISSUE TITLE
`toString` without the dashes

### ISSUE THREAD

**Issue by markusthoemmes** [jchambers/fast-uuid#7]
I realize a proper UUID has dash-delimiters. For my project specifically, we want those gone (to make UUID copyable from the commandline easily).

Any chance you'd accept a PR for `toStringWithoutDashes`?

**Comment by jchambers** [comment]
I've gone back and forth on this a few times, but I think it makes sense to pass for now. I really appreciate the offer, though! My thought is that, while some users may find it useful, having a library about UUIDs that produces things that aren't _technically_ legal UUIDs is likely to cause more confusion than is justified by the benefit.

That said, thank you again for the offer!

**Comment by doom369** [comment]
@markusthoemmes you may use own method, something like I did based on @jchambers  code - https://github.com/blynkkk/blynk-server/blob/master/server/utils/src/main/java/cc/blynk/utils/TokenGeneratorUtil.java#L36
